version: '3'
services:
  tc-informix:
    image: "appiriodevops/tc-database-scripts:latest"
    hostname: informix.cloud.topcoder.com
    container_name: iif_innovator_c
    environment:
      LICENSE: accept
    ports:
      - "2021:2021"
      - "2022:2022"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    tty: true
  tc-online-review:
    platform: linux/amd64
    image: tc-online-review:latest
    depends_on:
      - tc-informix
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS= -Xms1G -Xmx1G -XX:MaxPermSize=256M -server